spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/auth/**
        - id: products-service
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationPreFilter
      globalcors:
        cors-configuration:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:8082"
            allowedMethods:
              - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
          default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
server:
  port: 4000

gateway:
  excludedUrls: "/auth/register,/auth/login"

jwt:
  secret: xIPvetTUmC5tQ45qkhzCl9mPmEifg39fNjFf94AE2WE=

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot: DEBUG
